import React, { createContext, useContext, useState } from "react";

type Lang = "ru" | "kz";

type LangContextType = {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
};

const translations: Record<Lang, Record<string, string>> = {
    ru: {
      tagline: "вкусная шаурма",
      search: "Поиск",
      searchBtn: "Искать",
      contacts: "Контакты",
      orders: "Заказы",
      login: "Войти",
      logout: "Выйти",
        analytics: "Аналитика",
        shifts: "Смены",
        payroll: "Зарплата",
        adminProfile: "Профиль администратора",
        adminProfileHint: "Здесь можно вести учёт смен и роли",
        shiftsIntro:
          "Фиксируйте закрытые смены команды, чтобы отслеживать нагрузку и распределять премии по ролям.",
        from: "С",
        to: "По",
        employee: "Сотрудник",
        allEmployees: "Все сотрудники",
        loading: "Загрузка...",
        refresh: "Обновить",
        totalShifts: "Всего смен",
        totalHours: "Часы",
        shiftSummary: "Сводка по сменам",
        shiftCount: "Смен",
        avgHours: "Средняя длительность",
        lastShift: "Последняя смена",
        noShiftStats: "Нет данных по сменам",
        roleStatsTitle: "Распределение по ролям",
        employeeCount: "Сотрудников",
        noRoleStats: "Нет данных по ролям",
        addShift: "Добавить смену",
        chooseEmployee: "Выберите сотрудника",
        shiftDate: "Дата смены",
        shiftHours: "Часы",
        saving: "Сохранение...",
        selfShiftHint:
          "Менеджеры могут отмечать только свои смены. За сотрудников отвечает супер-администратор.",
        shiftsList: "Журнал смен",
        createdAt: "Создано",
        delete: "Удалить",
        noShifts: "Смен пока нет",
      allBranches: "Все филиалы",
      branch: "Филиал",
      expenses: "Расходы",
      profit: "Прибыль",
      revenue: "Выручка",
      averageCheck: "Средний чек",
      repeatRate: "Доля повторных заказов",
      conversion: "Конверсия",
      sources: "Источники заказов",
      source: "Источник",
      direct: "Прямые",
      saveReport: "Сохранить отчёт",
      savedReports: "Сохранённые отчёты",
      analyticsIntro:
        "Раздел для анализа заказов и выручки. Выберите фильтры, при необходимости сравните с прошлым периодом и сохраните отчёт.",
      download: "Скачать",
      filter: "Фильтр",
      keyMetrics: "Ключевые показатели",
      dailyChart: "Заказы и расходы по дням",
      day: "День",
      week: "Неделя",
      month: "Месяц",
      custom: "Диапазон",
      utmSource: "Источник",
      utmMedium: "Канал",
      utmCampaign: "Кампания",
      trackingSettings: "Настройки трекинга",
      gaId: "Google Analytics ID",
      yaId: "Яндекс Метрика ID",
      save: "Сохранить",
      comparePrev: "Сравнить с прошлым",
      ordersInfo: "Оплаченные / все",
      averageCheckInfo: "Сумма оплаченных / кол-во оплаченных",
      repeatInfo: "Повторные: %, шт. и доля выручки",
      userStatsTitle: "Статистика пользователей",
      totalUsersStat: "Всего пользователей",
      newUsersStat: "Новых за период",
      activeCustomersStat: "Активных клиентов",
      returningCustomersStat: "Повторных клиентов",
      registeredOrdersStat: "Заказы зарегистрированных",
      guestOrdersStat: "Заказы гостей",
      topDishesTitle: "Популярные блюда",
      dishName: "Блюдо",
      dishQuantity: "Порций",
      dishRevenue: "Выручка, ₸",
      ordersByHour: "Заказы по часам",
      orderHeatmapTitle: "Тепловая карта заказов",
      noAnalyticsData: "Недостаточно данных",
      combo: "Комбо",
      dishes: "Блюда",
      snacks: "Закуски",
      sauces: "Соусы",
      drinks: "Напитки",
      deliveryAddresses: "Адреса и зоны доставки",
      reviews: "Отзывы",
      promotions: "Акции",
      deliveryPayment: "Доставка и оплата",
      bonusProgram: "Бонусная программа",
      vacancies: "Вакансии",
      reportBug: "Сообщить об ошибке",
      promoAppLine: "Акции, скидки, кэшбэк − в нашем приложении!",
      appStore: "App Store",
      googlePlay: "Google Play",
      comingSoon: "Скоро",
      company: "ИП Таубекова Б.К.",
      privacyPolicy: "Политика конфиденциальности",
      publicOffer: "Публичная оферта",
      admin: "Админ",
      promoPlaceholder: "Промокод",
      apply: "Применить",
      promoInfo: "Промокоды могут действовать не во всех филиалах.",
      useBonus: "Списать бонусы",
      total: "Итого",
      discount: "Скидка",
      bonusUsed: "Списано бонусов",
      bonusEarn: "Начислим бонусов",
      toPay: "К оплате",
      leaveReview: "Оставить отзыв",
      yourName: "Ваше имя",
      rating: "Оценка",
      yourComment: "Комментарий",
      submitReview: "Отправить",
        noReviews: "Пока нет отзывов",
        contactsTitle: "Контакты",
        contactPhone: "По всем вопросам звоните:",
        promotionsTitle: "Акции",
        promo1: "Скидка 1000 тенге на первый заказ через сайт и приложение",
        promo2: "Подарите другу 2000т по промо-коду и получите 1000т себе",
        deliveryTitle: "Доставка и оплата",
        deliverySection: "🚚 Доставка",
        deliveryText1: "Заказы доставляются ежедневно с 10:00 до 02:00.",
        deliveryText2: "Радиус действия доставки ограничен зоной обслуживания.",
        paymentSection: "💳 Способы оплаты",
        paymentIntro: "Заказ можно оплатить следующими способами:",
        paymentKaspi: "Оплатить онлайн с Kaspi.kz — оплата производится удаленно, используя приложение, с карты банка Kaspi списывается сумма заказа.",
        paymentKaspiNote: "* Внимание! При отмене заказа, оплаченному онлайн, возврат средств осуществляется на указанный вами банковский счёт; срок возврата зависит от банка и может составлять до 7–14 дней.",
        paymentCash: "Наличными — оплата производится наличными курьеру при доставке заказа или в точке продаж.",
        paymentCard: "Картой при получении — оплата производится банковской картой через терминал, который привезёт курьер при доставке заказа или в точке продаж.",
        bonusTitle: "Бонусная программа",
        bonusIntro: "Копите и тратьте с удовольствием:",
        bonusRule1: "🧾 С каждого заказа на ваш бонусный счёт начисляется 10% кэшбэка",
        bonusRule2: "📅 Бонусы действуют в течение 14 дней с момента начисления",
        bonusRule3: "💳 Можно оплатить до 30% суммы заказа бонусами",
        bonusRule4: "🎁 Бонусы действуют на все блюда, включая Комбо, но не на напитки",
        bonusRule5: "🔁 Чтобы применить бонусы — нажмите значок рядом с опцией оплаты бонусами в корзине",
        reportErrorTitle: "Сообщить об ошибке",
        emailOptional: "Ваш email (необязательно)",
        problemPlaceholder: "Опишите проблему",
        send: "Отправить",
        afterSend: "После нажатия кнопки откроется окно отправки письма в вашем почтовом клиенте.",
        vacanciesTitle: "Вакансии",
        contactsPagePhone: "+7 771 375 57 11",
        menu: "Меню",
        cart: "Корзина",
        support: "Поддержка",
        supportChat: "Чат с поддержкой",
        messagePlaceholder: "Сообщение...",
      },
      kz: {
        tagline: "дәмді шаурма",
      search: "Іздеу",
      searchBtn: "Іздеу",
      contacts: "Контактілер",
      orders: "Тапсырыстар",
      login: "Кіру",
      logout: "Шығу",
        analytics: "Аналитика",
        shifts: "Кезектер",
        payroll: "Жалақы",
        adminProfile: "Әкімші профилі",
        adminProfileHint: "Мұнда кезек пен рөлдерді есепке алуға болады",
        shiftsIntro:
          "Команда кезектерін белгілеп, жүктемені бақылаңыз және рөлдер бойынша сыйақыны бөлуге көмектесіңіз.",
        from: "Басталу",
        to: "Аяқталу",
        employee: "Қызметкер",
        allEmployees: "Барлық қызметкерлер",
        loading: "Жүктелуде...",
        refresh: "Жаңарту",
        totalShifts: "Барлығы кезек",
        totalHours: "Сағат",
        shiftSummary: "Кезектер бойынша қорытынды",
        shiftCount: "Кезек саны",
        avgHours: "Орташа ұзақтығы",
        lastShift: "Соңғы кезек",
        noShiftStats: "Кезек бойынша мәлімет жоқ",
        roleStatsTitle: "Рөлдер бойынша бөліну",
        employeeCount: "Қызметкерлер",
        noRoleStats: "Рөлдер бойынша мәлімет жоқ",
        addShift: "Кезек қосу",
        chooseEmployee: "Қызметкерді таңдаңыз",
        shiftDate: "Кезек күні",
        shiftHours: "Сағат саны",
        saving: "Сақталуда...",
        selfShiftHint:
          "Менеджерлер тек өз кезектерін белгілей алады. Басқаларын супер-әкімші тіркейді.",
        shiftsList: "Кезектер журналы",
        createdAt: "Жасалған уақыты",
        delete: "Жою",
        noShifts: "Кезектер жоқ",
      allBranches: "Барлық филиалдар",
      branch: "Филиал",
      expenses: "Шығындар",
      profit: "Пайда",
      revenue: "Түсім",
      averageCheck: "Орташа чек",
      repeatRate: "Қайталама тапсырыстар үлесі",
      conversion: "Конверсия",
      sources: "Тапсырыс көздері",
      source: "Дереккөз",
      direct: "Тікелей",
      saveReport: "Есепті сақтау",
      savedReports: "Сақталған есептер",
      analyticsIntro:
        "Бұл бөлімде тапсырыстар мен түсім статистикасы көрсетіледі. Периодты таңдаңыз, қажет болса салыстырыңыз және есепті сақтаңыз.",
      download: "Жүктеу",
      filter: "Сүзгі",
      keyMetrics: "Негізгі көрсеткіштер",
      dailyChart: "Күндер бойынша тапсырыстар мен шығындар",
      day: "Күн",
      week: "Апта",
      month: "Ай",
      custom: "Аралық",
      utmSource: "Дереккөз",
      utmMedium: "Арна",
      utmCampaign: "Науқан",
      trackingSettings: "Трекинг баптаулары",
      gaId: "Google Analytics ID",
      yaId: "Yandex Metrica ID",
      save: "Сақтау",
      comparePrev: "Алдыңғысымен салыстыру",
      ordersInfo: "Төленген / барлығы",
      averageCheckInfo: "Төленген сомасы / төленген саны",
      repeatInfo: "Қайталама: %, дана және түсім үлесі",
      userStatsTitle: "Пайдаланушылар статистикасы",
      totalUsersStat: "Барлығы пайдаланушылар",
      newUsersStat: "Периодтағы жаңалары",
      activeCustomersStat: "Белсенді клиенттер",
      returningCustomersStat: "Қайтып келген клиенттер",
      registeredOrdersStat: "Тіркелгендер тапсырыстары",
      guestOrdersStat: "Қонақ тапсырыстары",
      topDishesTitle: "Танымал тағамдар",
      dishName: "Тағам",
      dishQuantity: "Порция",
      dishRevenue: "Түсім, ₸",
      ordersByHour: "Сағат бойынша тапсырыстар",
      orderHeatmapTitle: "Тапсырыстардың жылу картасы",
      noAnalyticsData: "Деректер жеткіліксіз",
      combo: "Комбо",
      dishes: "Тағамдар",
      snacks: "Тіскебасар",
      sauces: "Тұздықтар",
      drinks: "Сусындар",
      deliveryAddresses: "Жеткізу мекенжайлары мен аймақтары",
      reviews: "Пікірлер",
      promotions: "Науқандар",
      deliveryPayment: "Жеткізу және төлем",
      bonusProgram: "Бонус бағдарламасы",
      vacancies: "Вакансиялар",
      reportBug: "Қате туралы хабарлау",
      promoAppLine: "Акциялар, жеңілдіктер, кэшбэк — біздің қосымшада!",
      appStore: "App Store",
      googlePlay: "Google Play",
      comingSoon: "Жақында",
      company: "ЖК Таубекова Б.К.",
      privacyPolicy: "Құпиялық саясаты",
      publicOffer: "Жария оферта",
      admin: "Әкімші",
      promoPlaceholder: "Промокод",
      apply: "Қолдану",
      promoInfo: "Промокодтар барлық филиалдарға жарамайды.",
      useBonus: "Бонусты пайдалану",
      total: "Барлығы",
      discount: "Жеңілдік",
      bonusUsed: "Жиналған бонус",
      bonusEarn: "Жиналатын бонус",
      toPay: "Төлеу",
      leaveReview: "Пікір қалдыру",
      yourName: "Атыңыз",
      rating: "Баға",
      yourComment: "Пікір",
      submitReview: "Жіберу",
        noReviews: "Әзірге пікір жоқ",
        contactsTitle: "Контактілер",
        contactPhone: "Барлық сұрақтар бойынша қоңырау шалыңыз:",
        promotionsTitle: "Науқандар",
        promo1: "Сайт және қосымша арқылы алғашқы тапсырысқа 1000 теңге жеңілдік",
        promo2: "Досыңызға 2000т промокод беріп, өзіңізге 1000т алыңыз",
        deliveryTitle: "Жеткізу және төлем",
        deliverySection: "🚚 Жеткізу",
        deliveryText1: "Тапсырыстар күн сайын 10:00-ден 02:00-ге дейін жеткізіледі.",
        deliveryText2: "Жеткізу радиусы қызмет көрсету аймағымен шектелген.",
        paymentSection: "💳 Төлем тәсілдері",
        paymentIntro: "Тапсырысты келесі тәсілдермен төлеуге болады:",
        paymentKaspi: "Kaspi.kz арқылы онлайн төлеу — қосымша арқылы қашықтан төленеді, Kaspi банк картасынан тапсырыс сомасы алынады.",
        paymentKaspiNote: "* Назар аударыңыз! Онлайн төленген тапсырыс жойылса, қаражат көрсетілген банк шотына қайтарылады; қайтару мерзімі банкке байланысты 7–14 күн болуы мүмкін.",
        paymentCash: "Қолма-қол — тапсырысты жеткізу кезінде курьерге немесе сату нүктесінде қолма-қол төленеді.",
        paymentCard: "Картамен алған кезде — тапсырысты жеткізу кезінде курьер әкелетін терминал арқылы немесе сату нүктесінде банк картасымен төленеді.",
        bonusTitle: "Бонус бағдарламасы",
        bonusIntro: "Бонус жинап, ләззатпен жұмсаңыз:",
        bonusRule1: "🧾 Әр тапсырыстан бонус шотыңызға 10% кэшбэк түседі",
        bonusRule2: "📅 Бонустар есептелген сәттен бастап 14 күн ішінде жарамды",
        bonusRule3: "💳 Тапсырыс сомасының 30%-ына дейін бонустармен төлеуге болады",
        bonusRule4: "🎁 Бонустар барлық тағамдарға, соның ішінде комбоға да жарамды, бірақ сусындарға емес",
        bonusRule5: "🔁 Бонустарды қолдану үшін — себеттегі бонустармен төлеу опциясының жанындағы белгішені басыңыз",
        reportErrorTitle: "Қате туралы хабарлау",
        emailOptional: "Сіздің email (міндетті емес)",
        problemPlaceholder: "Мәселені сипаттаңыз",
        send: "Жіберу",
        afterSend: "Түймені басқаннан кейін пошта клиентінде хат жіберу терезесі ашылады.",
        vacanciesTitle: "Вакансиялар",
        contactsPagePhone: "+7 771 375 57 11",
        menu: "Мәзір",
        cart: "Себет",
        support: "Қолдау",
        supportChat: "Қолдау чаты",
        messagePlaceholder: "Хабарлама...",
      },
    };

const LangContext = createContext<LangContextType>({
  lang: "ru",
  setLang: () => {},
  t: (key) => translations.ru[key] ?? key,
});

export const LangProvider = ({ children }: { children: React.ReactNode }) => {
  const [lang, setLang] = useState<Lang>("ru");
  const t = (key: string) => translations[lang][key] ?? key;
  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
};

export const useLang = () => useContext(LangContext);
